version: '3'
services:
  cp-zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  cp-broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    depends_on:
      - cp-zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'

  azkarra-worker:
    image: streamthoughts/azkarra-streams-worker:latest
    hostname: azkarra
    container_name: azkarra
    depends_on:
      - cp-broker
    ports:
      - "8080:8080"
    environment:
      AZKARRA_CONTEXT_STREAMS_BOOTSTRAP_SERVERS: broker:29092
      AZKARRA_CONTEXT_STREAMS_STATE_DIR: /var/lib/kafka-streams/
      AZKARRA_CONTEXT_AUTO_CREATE_TOPICS_ENABLE: "true"
      # /!\ Use this property with care and don't enable for production.
      AZKARRA_CONTEXT_AUTO_DELETE_TOPICS_ENABLE: "true"
      AZKARRA_CONTEXT_ENABLE_WAIT_FOR_TOPICS: "true"
      AZKARRA_COMPONENT_PATHS: /usr/share/azkarra-components
    volumes:
      - /tmp/azkarra/components:/usr/share/azkarra-components
      #- /tmp/azkarra/etc/azkarra.conf:/etc/azkarra/azkarra.conf
